DROP TABLE IF EXISTS nominations CASCADE;
CREATE TABLE nominations (
  id SERIAL PRIMARY KEY NOT NULL,
  email_id INTEGER REFERENCES emails(id) ON DELETE CASCADE,
  imdbID VARCHAR(255) NOT NULL,
  title VARCHAR(255),
  year INTEGER
);
